Autofill visible password fields only
mulbc/vaultPass pull request #35
Opened 2023-01-11 07:00 UTC by Gerard-CK

Some site have their Register form, Reset Password form etc... as hidden panels. So only select the first visible password field when autofilling from Vault

2023-01-11 17:13 UTC, afteroot commented
Interesting, will take a look at this

2023-01-11 20:16 UTC, mulbc commented on content.js
> +    if (node.offsetParent) return node;
I'm not sure I understand the offsetParent function correctly, but how would that help in identifying visible inputs?

2023-01-11 20:17 UTC, mulbc commented on content.js
>    // eslint-disable-next-line quotes
if you move the querySelector, you have to move the eslint exception too

2023-01-12 07:23 UTC, Gerard-CK commented on content.js
>    // eslint-disable-next-line quotes
Indeed I do.

2023-01-12 11:33 UTC, mulbc requested changes
This looks very good already... but how about we just select the first node we found (if we found any) in case none passes our new node.offsetParent test?
That way we have a fallback to the previous way of working

Also why did you make the changes on lines 46-49?

2023-01-12 11:38 UTC, Gerard-CK commented
> This looks very good already... but how about we just select the first node we found (if we found any) in case none passes our new node.offsetParent test? That way we have a fallback to the previous way of working

>> Yes, that makes sense. I'll work on that

> Also why did you make the changes on lines 46-49?
>> I realised during testing that some sites wrap their username field into a div or other container and give that an id of 'user', 'userid' etc... so I adjusted the query to pick input fields only otherwise we won't be able to set any value

2023-01-13 09:27 UTC, mulbc approved these changes
lgtm - thanks for working on this!

2023-01-13 09:27 UTC, merged